image: gitpod/workspace-full

tasks:
  - name: Setup backend
    command: |
      # Create backend folder if it doesn't exist
      [ -d backend ] || mkdir backend

      cd backend

      # Initialize Node + TS project if package.json missing
      if [ ! -f package.json ]; then
        npm init -y
        npm install typescript ts-node-dev @types/node --save-dev
        npx tsc --init
        mkdir src
        echo "console.log('Backend running');" > src/index.ts
        # Add dev script
        jq '.scripts.dev="ts-node-dev src/index.ts"' package.json > temp.json && mv temp.json package.json
      fi

      # Install dependencies
      npm install

      # Start backend
      npm run dev &

  - name: Setup frontend
    command: |
      # Create frontend folder if it doesn't exist
      [ -d frontend ] || mkdir frontend

      cd frontend

      # Initialize Vite + React + TS project if package.json missing
      if [ ! -f package.json ]; then
        npm create vite@latest . -- --template react-ts
        npm install
      fi

      # Start frontend
      npm run dev &

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - eamodio.gitlens
    - ms-azuretools.vscode-docker
    - amazonwebservices.aws-toolkit-vscode

ports:
  - port: 3000
    onOpen: open-preview
  - port: 5173
    onOpen: open-preview
