image: gitpod/workspace-full

tasks:
  - name: Setup project folders
    command: |
      #!/bin/bash
      # Create backend if missing
      if [ ! -d backend ]; then
        mkdir backend
        touch backend/.gitkeep
        echo "Backend folder created with .gitkeep"
      else
        echo "Backend folder already exists"
      fi

      # Create frontend if missing
      if [ ! -d frontend ]; then
        mkdir frontend
        touch frontend/.gitkeep
        echo "Frontend folder created with .gitkeep"
      else
        echo "Frontend folder already exists"
      fi

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - eamodio.gitlens
    - ms-azuretools.vscode-docker
    - amazonwebservices.aws-toolkit-vscode
